services:
  db:
    image: postgres
    container_name: prin-sustain-db
    environment:
      POSTGRES_DB: "prin_db"
      POSTGRES_USER: "prin_user"
      POSTGRES_PASSWORD: "supers3curepassword"
    ports:
      - "6600:5432"
    restart: unless-stopped